tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: BUGLES_DB
      schema: dev
      warehouse: BUGLES_XL
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: BUGLES_DB
      schema: prod
      warehouse: BUGLES_XL